### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by David-Jin** [foreverYoungGitHub/MTCNN#16] opened 2017-05-15 04:51 UTC
I'am using caffe-1.0 release version，but a linking error come across。
what's the original caffe version did you use??
@foreverYoungGitHub 

CMakeFiles/MTCNN.dir/MTCNN.cpp.o: In function `MTCNN::MTCNN(std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >)':
MTCNN.cpp:(.text+0x6df): undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [MTCNN] Error 1
make[1]: *** [CMakeFiles/MTCNN.dir/all] Error 2
make: *** [all] Error 2

**Comment by foreverYoungGitHub** [comment] 2017-05-15 21:31
I'm not sure does it can solve your problem. But this is caused by unsuccessful linking with caffe library file.

In the newest version of caffe, the CMakeFile has delete the Caffe_INCLUDE_DIRS in their CaffeConfig.cmake file. 

[This issue](https://github.com/BVLC/caffe/issues/5532) can be resolved by get_property() command, which I can add it in these two weeks.

Hope it can help you.

Yang

**Closed as completed by foreverYoungGitHub** 2017-05-15 21:31 UTC

**Comment by David-Jin** [comment] 2017-05-16 00:06
Thanks， finally i solved my problem: the linking process linked the libcaffe-rc3.so in /usr/local/lib
I just delete the so lib and run ldconfig.   Then, It is ok!  Thank you all the same.
